---
- name: Update homebrew
  homebrew: update_homebrew=yes

- name: Install homebrew libraries
  homebrew: name={{ item }} state=latest
  with_items:
    - curl
    - git
    - vim
    - zsh
    - npm

- name: Install npm packages
  npm: name={{ item }} state=latest global=yes
  with_items:
    - raml2html
    - raml2wiki
